### ISSUE TITLE
tw.nextapple.com

### ISSUE THREAD

**Issue by RyanChuang** [FutaGuard/LowTechFilter#129]
## 現在 `FutaFilter` 對他的處置是？

首頁顯示不出來

## 建議對此網域做出何種改變

請更改語法

## 提出更改的理由

![螢幕擷取畫面 2024-08-31 152440](https://github.com/user-attachments/assets/940bd945-1b76-4688-99f3-015bcd5f091b)
首頁顯示不出來。停用 LowTechFilter Pureview News 就不會有這個問題

**Comment by mikucat0309** [comment]
無法復現這個情形，有更多資訊嗎？

- OS: Widnows 10
- Browser: Librewolf 129.0.1-1
- User-Agent: Mozilla/5.0 (Windows NT 10.0; rv:129.0) Gecko/20100101 Firefox/129.0
- Extension: uBlock Origin 1.58.0

**Comment by RyanChuang** [comment]
OS: Windows 10 x64
Browser: Chrome 128.0.0.0
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36
Extension: uBlock Origin 1.59.0
