### ISSUE TITLE
[removeparam] [uBO] 🚀  request to update filter (selgros.pl)

### ISSUE THREAD

**Issue by ghost** [FutaGuard/LowTechFilter#43]
## what does `FutaFilter` do currently?

I found new problematic removeparam - `$removeparam=/extid/i`: https://github.com/FutaGuard/FutaFilter/blob/26bf4163819aea77e9d54a820d689e1075764951/removeparam.txt#L14

I can't check Polish city shop hall from I prefere see offers.

## supposed to be 

I suppose we can again exclude few domains like:

`$removeparam=/extid/i,domain=~selgros.pl`

I'm still wondering if it's possible to somehow exclude this in uBO from filtering address path parameters be like:

> AdGuard maybe can use `@@||selgros.pl/set_hall$document` or `@@||selgros.pl/set_hall$genericblock` but uBO don't allow these

I suppose bad is add negation regex before `$` to exclude url paths.

## reason

1. Open this page `https://www.selgros.pl/horeca`

2. try click in any Polish city on pop-up list "wybierz halę"

   * or click in  red "ZMIEŃ" behind "TWOJA HALA: nie wybrano" and now click on any city from list
   
3. list break URL path like: `https://www.selgros.pl/set_hall?extId=118` so can't save checked city shop hall

**Comment by tasi788** [comment]
I hope so, but seem there's noting we can do on this.
maybe open an Feature-Request issue on uBO's repo would be better 🥳

**Comment by strict-block** [comment]
on `uBlock-issues` of lack of support removeparam?

**Comment by strict-block** [comment]
@gorhill

**Comment by tasi788** [comment]
sorry I didn't look carefully. 
In this case maybe I should made a removeparam allow list instead.
what do think ?

**Comment by strict-block** [comment]
If possible reporduce with AG then maybe good be is add exclude 1 Polish domain.

**Comment by strict-block** [comment]
uBo 1.36.0 property use:

`@@||selgros.pl/set_hall$removeparam`
