### ISSUE TITLE
[removeparam] [uBO] 🚀   request to update filter (google.com)

### ISSUE THREAD

**Issue by ghost** [FutaGuard/LowTechFilter#45]
## what does `FutaFilter` do currently?

https://github.com/FutaGuard/FutaFilter/blob/26bf4163819aea77e9d54a820d689e1075764951/removeparam.txt#L41 `$removeparam=/utm_campaign/i`

filter may remove too many characters from few  Google URL-s path.

## supposed to be 

N/A, exclude clear google links may reduce the effectiveness of the list.

## reason

steps to reproduce:

1. Sometime on Google Maps is promoted now opened local shops (with daily needed food) or restaurants

2. In this small pop-up we have found these links:
   ```
    https://www.google.com/url?q=https://www.google.com/maps/search/otwarty%2Bsklep%2Bspo%C5%BCywczy%3Futm_source%3Dgoogle%26utm_medium%3Dhppromo%26utm_campaign%3Dretail_m&source=hpp
   ```
3. Then `$removeparam=/utm_campaign/i` remove main of paramert `q=`:

   ```
   q=https://www.google.com/maps/search/otwarty%2Bsklep%2Bspo%C5%BCywczy%3Futm_source%3Dgoogle%26utm_medium%3Dhppromo%26utm_campaign%3Dretail_m
   ```

4. so we have error about "this url redirect to invalid page".

**Comment by tasi788** [comment]
I can't reproduce with AdGuard.

Step:
1. Open ```https://www.google.com/url?q=https://www.google.com/maps/search/otwarty%2Bsklep%2Bspo%C5%BCywczy%3Futm_source%3Dgoogle%26utm_medium%3Dhppromo%26utm_campaign%3Dretail_m&source=hpp```
2. AdGuard do remove parameter
![image](https://user-images.githubusercontent.com/11913223/115020434-2b8c8800-9eed-11eb-88c0-867cba3d33f7.png)
![image](https://user-images.githubusercontent.com/11913223/115020543-51b22800-9eed-11eb-8928-1ccd8a69584e.png)
![image](https://user-images.githubusercontent.com/11913223/115020576-5aa2f980-9eed-11eb-8be4-8ee477817903.png)
3. Finally redirect to `https://www.google.com/maps/search/otwarty+sklep+spo%C5%BCywczy`

**Comment by strict-block** [comment]
@gorhill

**Comment by gorhill** [comment]
The filter is not crafted properly. When using regex-based `removeparam` token, more attention needs to be paid to the regex so as to avoid false positive. The filter should really be:

    *$removeparam=/\butm_campaign=/i

This will avoid false positives.

**Comment by tasi788** [comment]
Thanks @gorhill for the suggestion ☺️
however FutaFilter list was built for AdGuard at first, so I was not clear about uBO's syntax. But I will try to make it compatible with other adblocker next time 👌

**Comment by gorhill** [comment]
AdGuard will also support the same syntax/semantic, this was the result of discussions to implement `removeparam` the same way in both blockers, see <https://github.com/uBlockOrigin/uBlock-issues/issues/1356#issuecomment-735896202>.

**Comment by strict-block** [comment]
For uBo 1.36.0+ only:

@@||https://www.google.com/url?q=https://www.google.com/maps/*utm_campaign$removeparam


See these: https://github.com/uBlockOrigin/uBlock-issues/issues/1626
