### ISSUE TITLE
📢 移除「removeparam」清單

### ISSUE THREAD

**Issue by tasi788** [FutaGuard/LowTechFilter#63]
## 理由
目前 AdGuard 對於移除網址追蹤碼更加完善，且目前無法抽出更多時間多維護一個清單

**Comment by ptntp** [comment]
@tasi788 如果不使用這個清單，那要選內建的哪個呢？

**Comment by tasi788** [comment]
> @tasi788 如果不使用這個清單，那要選內建的哪個呢？

URL Tracking filter
https://adguard.com/en/blog/adguard-url-tracking-filter.html

**Comment by bestpika** [comment]
@ptntp 
![image](https://user-images.githubusercontent.com/5698157/180598118-455d319a-c24a-49c6-856a-d716247304a8.png)

**Comment by ptntp** [comment]
原來如此，AdGuard Home 也一樣對嗎？

**Comment by bestpika** [comment]
AGH 又不能處理這個

**Comment by ptntp** [comment]
@bestpika 了解👍
