### ISSUE TITLE
🚀  更新清單請求: hosts建議移除REGEX規則

### ISSUE THREAD

**Issue by thrive7776** [FutaGuard/LowTechFilter#92]
## 現在 `FutaFilter` 對他的處置是？

黑名單

## 建議對此網域做出何種改變

· /wsf.+gov\.xyz/
· /tw.{3}gov\.com/
· /tw\S{2}gov\.com/
· /[a-z]{3}gov\.(com|tv|me|top)/
這4條可以由下面這條取代(有誤擋的話可以在把其他國家"gov.ccTLD"加上)
|*gov.$denyallow=gov|gov.au|gov.cn|gov.hk|gov.in|gov.mo|gov.my|gov.sg|gov.tw|gov.uk

· /butie\S+\.(shop|xyz)/
拆寫2條就行了
|\*butie\*.shop^
|\*butie\*.xyz^

備註：
1.假設貴單位及使用者都用AdGuardHome在過濾，理應支援$denyallow
https://github.com/AdguardTeam/AdGuardHome/wiki/Hosts-Blocklists#denyallow
2.某些國家並不使用"gov.ccTLD"，比如日本是用"go.jp"。
https://en.wikipedia.org/wiki/.jp#Second-level_domains

## 提出更改的理由

理由：
REGEX吃資源，100條普通規則(wildcard)比1條REGEX還省資源(應該啦？←_←)。

證據：
https://help.adblockplus.org/hc/en-us/articles/360062733293#regexps
"Note For performance reasons, we recommend avoiding regular expressions if possible."

**Comment by bestpika** [comment]
@thrive7776 何不乾脆 PR？

**Comment by tasi788** [comment]
原先這些設計是為了應付當初大量的詐騙簡訊的情況下所做的緊急應對，現在相關的詐騙已經減緩我想已經可以刪除了。

部分縮寫功能我會再花時間看一下，如果有更好的做法也歡迎直接 PR

**Comment by thrive7776** [comment]
1.那個…其實才剛註冊github，某些功能還不熟(遮臉)。

2.另外，以誤殺政府網站為代價來擋詐騙&降低資源使用，好像有點Overkill？
還是問過主要維護者比較好。

3.再者，FutaGuard使用同一倉庫存放Content/DNS Blocklist，
怕打亂維護者同步的節奏(DNS擋了 ↔ Content沒擋到之類的？)。

謝謝兩位回應。

**Comment by bestpika** [comment]
@thrive7776
2. 是說你說有「誤報政府網站」要舉個例子出來啊，不然應該早就有其他使用者詢問了
3. PR 這種事是先發再說的，反正收不收是另一件事，而且收之前也可以討論修改完再收

**Comment by thrive7776** [comment]
@bestpika

算潛在問題啦。

1."|*gov.$denyallow=gov"佔20字

2.從IANA撈出來255個country-code.
https://www.iana.org/domains/root/db

3.每個cc佔6(gov.CC)+1(|)字，255×7＝1785字。
(先不考慮某些國家不使用gov.ccTLD；要手動查，麻煩=_=)

4.我們需要20＋1785＝1805字，但每行規則最長1024字。

5.也就是說最終會有選擇性的問題：
denyallow該放入那些國家(＋)，那些要放生掉(－)。

**Comment by bestpika** [comment]
@thrive7776 可是你有看過有哪個國家的 `gov` 後面接 `.com` 或列出來的那幾個嗎？
更不用說那幾個規則理論上不會抓到 `.gov` 的東西
所以我不知道你的疑慮是怎麼產生的 XD

**Comment by bestpika** [comment]
我是記得有個網站被誤殺啦，但是那個網站根本不是政府機關的網站
~~所以影響小到幾乎沒人在意~~

**Comment by thrive7776** [comment]
@bestpika
"|*gov.$" 注意錢幣符號前面的.(AGH會把它處理成DOT跟ROOT兩種狀況)
當ROOT處理時，ccTLD問題就來了。

**Comment by bestpika** [comment]
@thrive7776 我指的是原始的那幾條規則沒有誤擋的問題

然後你說的這個是基於 regex 效率的問題吧
你貼的那個是「瀏覽器」的問題
但是 AGH 之類的 DNS 過濾工具跟瀏覽器其實完全不同
所以實際上的影響就我看來微乎其微（你可以從 AGH 的過濾記錄檢查他過濾這條規則花了多少時間）
